server:
  port: 8603
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true

# Feign hystrix support
feign:
  hystrix:
    enabled: true

# hystrix dashboard support
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health