# Feign hystrix support
feign:
  hystrix:
    enabled: true

# 开启监控接口，这里所有的接口，都有前缀： actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: hystrix.stream, info, health
